global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vts'
    scrape_interval: 5s
    metrics_path: /status/format/prometheus
    static_configs:
      - targets: ['rp-nginx:80']

